name: Set and Retrieve GitHub ENV variables

on:
  push:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Set and Retrieve GitHub ENV variables
        run: |
          # Define variables
          tests=16
          failures=2
          echo "Tests=$tests" >> $GITHUB_ENV
          echo "Failures=$failures" >> $GITHUB_ENV
          echo "${{ env.Failures }} out of ${{ env.Tests }} tests failed on CI"
