name: Set and Retrieve GitHub ENV variables

on:
  push:

jobs:
  build:
    runs-on: self-hosted

- name: Retrieve version
  run: |
    echo ::set-env name=TAG_NAME::$(nproc)

- name: Create Release
  id: create_release
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.token }}
  with:
    tag_name: ${{ env.TAG_NAME }}

