on: [push]

jobs:
  build:
    name: Greeting
    runs-on: beegfs1
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

