name: client rebuild test 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - All
        - ofed x86_64-rhel8.2-mlnx5.0
        - ofed x86_64-rhel8.3-mlnx5.1
        - ofed x86_64-rhel8.3-mlnx5.2
        - ofed x86_64-alma8.4-mlnx5.4
        - ofed x86_64-alma8.5-mlnx5.5
        - ofed x86_64-alma8.7-mlnx5.8-lts
        - ofed x86_64-rocky8.8-mlnx5.8-lts
        - ofed x86_64-alma9-mlnx5.6
        - ofed x86_64-alma9-mlnx5.7
        - ofed x86_64-rocky9.1-mlnx5.8-lts
        - ofed ubuntu-22.04-mlnx-5.6-gcc-11
        - ofed ubuntu-22.04-mlnx-5.7
        - distro ubuntu23.04-amd64
        - distro debian12-client-build
        - ofed x86_64-open-suse-15.4
        - ofed x86_64-sles15-mlnx5.0
        - ofed x86_64-sles15sp2-mlnx5.1
        - ofed x86_64-sles15sp3-mlnx5.5
        - ofed x86_64-open-suse-15.3-mlnx5.6
        - distro x86_64-sles15
        - distro x86_64-sles15sp2
        - distro x86_64-sles15sp3

jobs:
RHEL_8_2_mlnx_5_0:
    name: RHEL 8.2 with MLNX 5.0
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-rhel8.2-mlnx5.0'
    container:
       image: thinkpranav/x86_64-rhel8.2-mlnx5.0@sha256:6acb8cb6c4886a99c6de23ec52e69ce973bf117e0bdd070361431706c0c2a5b6
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Client rebuild
        run: |
          bash .ci/build/client_build.sh /usr/src/linux 

RHEL_8_3_mlnx_5_1:
    name: RHEL 8.3 with MLNX 5.1
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-rhel8.3-mlnx5.1'
    container:
       image: thinkpranav/x86_64-rhel8.3-mlnx5.1@sha256:12f5c41d8233e3318a724ad8b74409b49474b57752bed0d0a7114a9c227f0164
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Client rebuild
        run: |
          bash .ci/build/client_build.sh /usr/src/linux 

RHEL_8_3_mlnx_5_2:
    name: RHEL 8.3 with MLNX 5.2
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-rhel8.3-mlnx5.2'
    container:
       image: thinkpranav/x86_64-rhel8.3-mlnx5.2@sha256:47be8197634c1433b18268935d0af3154e93a75193a3474738fd0e68e72d9ad8
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Client rebuild
        run: |
          bash .ci/build/client_build.sh /usr/src/linux 
  

AlmaLinux_8_4_mlnx_5.4:
    name: AlmaLinux 8.4 with MLNX 5.4 
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-alma8.4-mlnx5.4'
    container:
       image: thinkpranav/x86_64-alma8.4-mlnx5.4@sha256:aada95457fd16b126f36bd85a90db9aebb348196c8697671924438efb98106a6
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux


AlmaLinux_8_5_mlnx_5.5:
    name: AlmaLinux 8.5 with MLNX 5.5 
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-alma8.5-mlnx5.5'
    container:
       image: thinkpranav/alma-8.5-mlnx-5.5@sha256:bbc4df47b8e1b236cc5108d55f96c9be6ad35dcb6e89d17611b990c63711cd0f
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux


AlmaLinux_8_7_mlnx_5.8_lts:
    name: AlmaLinux 8.7 with MLNX 5.8 LTS
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-alma8.7-mlnx5.8-lts'
    container:
       image: thinkpranav/x86_64-almalinux8.7-mlnx5.8-lts@sha256:bba6516644ba939994d6b2dceb80ffca25c4775571f8eb45a583c75cd8666be3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux


RockyLinux_8_8_mlnx_5.8_lts:
    name: RockyLinux 8.8 with MLNX 5.8 LTS
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-rocky8.8-mlnx5.8-lts'
    container:
       image: thinkpranav/x86_64-rockylinux-8.8-mlnx5.8-lts@sha256:1aef4e5673b2341a9fae31e6957117bee3f633821bfa383945090c5eaddd1e68
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux
  
AlmaLinux_9_mlnx_5.6:
    name: AlmaLinux 9 with MLNX 5.6
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-alma9-mlnx5.6'
    container:
       image: thinkpranav/x86_64-almalinux9-mlnx5.6@sha256:a67e9dbc7c7ca4d322127cf7bbb23c0808f9d4e65d03918618c7fa024394a607
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux

AlmaLinux_9_mlnx_5.7:
    name: AlmaLinux 9 with MLNX 5.7
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-alma9-mlnx5.7'
    container:
       image: thinkpranav/x86_64-almalinux9-mlnx5.7@sha256:419c3af0c98e103916a91037732ab0b652608039d59fc7540f40b42d27e1cea0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux

RockyLinux_9.1_mlnx_5.8_lts:
    name: RockyLinux 9.1 with MLNX 5.8 LTS
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-rocky9.1-mlnx5.8-lts'
    container:
       image: thinkpranav/x86_64-rockylinux-9.1-mlnx5.8-lts@sha256:f1e12c67b84bb0d0de7a4cc99db098fb86f417772d0f8a51d6b7436064c048d8
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux


Ubuntu_22_04_mlnx_5.6: 
    name: Ubuntu 22.04 with MLNX 5.6 
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed ubuntu-22.04-mlnx-5.6-gcc-11'
    container:
       image: thinkpranav/ubuntu-22.04-mlnx-5.6-gcc-11@sha256:261ec00161b19cd8d0645c765d0972130c39dca5c249b15665df1cfe96eef7e5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux

Ubuntu_22_04_mlnx_5.7: 
    name: Ubuntu 22.04 with MLNX 5.7
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed ubuntu-22.04-mlnx-5.7'
    container:
       image: thinkpranav/ubuntu-22.04-mlnx-5.7-gcc-11@sha256:35ff1eefd0cd37cc5afbc1369457ab5debcfeb41ee522b4db8ebe03012c2fdae
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux-headers-default

Ubuntu_22_04_mlnx_5.8-lts: 
    name: Ubuntu 22.04 with MLNX 5.8 lts 
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed ubuntu-22.04-mlnx-5.8'
    container:
       image: thinkpranav/ubuntu-22.04-mlnx-5.8-lts@sha256:43739ebf54d7bf16511629e852fc6e337529e4ebae08b47afb0a3c861963fb52
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux
  
Ubuntu_23_04: 
    name: Ubuntu 23.04
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'distro ubuntu23.04-amd64'
    container:
       image: thinkpranav/ubuntu23.04-amd64-build-essential@sha256:691fd1a3b0d33ab42aca6d655bd69e865cf24f5e205ed18ffdff8055a5a1ce0f
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh /usr/src/linux


  
Debian_10_mlnx_5.2:
    name: Debian 10 with mlnx5.2  
    runs-on: self-hosted
    if: GitHub.event.inputs.name == 'All'  ||  github.event.inputs.name == 'ofed x86_64-debian10-mlnx5.2'
    container:
       image: thinkpranav/x86_64-debian10-mlnx5.2@sha256:a6415225e59ba231616393faafec11ccb493c2788f1e4d96d048cf2b1854a2a1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run client rebuild for Debian 12
        run: |
          bash .ci/build/client_build.sh 
  


Debian_12:
    name: Debian 12 client rebuild 
    runs-on: self-hosted
    if: GitHub.event.inputs.name == 'All'  ||  github.event.inputs.name == 'distro debian12-client-build'
    container:
       image: thinkpranav/debian12-client-build@sha256:26130277c017a216b00df43f9e32d2e03d0e6da6a2d17c7e2e345f9f67186619
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run client rebuild for Debian 12
        run: |
          bash .ci/build/client_build.sh /usr/src/linux
  
  
Open_suse_15_04: 
    name: Opensuse 15.04
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-open-suse-15.4'
    container:
       image: thinkpranav/x86_64-open-suse-15.4@sha256:a18382ad758610f63f09bf33be642d043194278e7f7f5c7f25489ef4b5664743
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh 
  
sles_15_mlnx_5.0: 
    name: sles15 mlnx with 5.0
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-sles15-mlnx5.0'
    container:
       image: thinkpranav/x86_64-sles15-mlnx5.0@sha256:82fd80030c30ef23282431f45d4e882d395ade6ccbe3bbd7a36b76cbe120bbf6
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh 
  
sles15sp2_mlnx_5.1: 
    name: sles15 sp2 with mlnx5.1
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-sles15sp2-mlnx5.1'
    container:
       image: thinkpranav/x86_64-sles15sp2-mlnx5.1@sha256:c2faa387f67cfa59408e0aae6dcd292312314a018f7aa30dcfdea16a98a82a2a
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh 
  
sles15sp3_mlnx_5.5: 
    name: sles15 sp3 with mlnx5.5
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-sles15sp3-mlnx5.5'
    container:
       image: thinkpranav/x86_64-sles15sp3-mlnx5.5@sha256:6acf368da06d6c197763e0428981981e86df1e4c4b7d256f369f6a926e721605
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh 
  
opensuse_15.3_mlnx_5.6: 
    name: opensuse 15.3 with mlnx 5.6
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'ofed x86_64-open-suse-15.3-mlnx5.6'
    container:
       image: thinkpranav/x86_64-open-suse-15.3-mlnx5.6@sha256:0ada6c0a24e076ebd584b20aef399b71ee79ff4663547c529b0fb8055adb54c6
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh 
  
sles15_distro: 
    name: sles15 distro
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'distro x86_64-sles15'
    container:
       image: thinkpranav/x86_64-sles15@sha256:a7e3937951f22987bdff69840fa72bc98cb6c9c4a63055934efbdad81451d58b
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh 


sles15sp3_distro: 
    name: sles15sp3 distro
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'distro x86_64-sles15sp3'
    container:
       image: thinkpranav/x86_64-sles15sp3@sha256:e34e4f87af9eaf2ad5ed3a21fcd833f24046dd05db0c3be1ee4d1f100a790df2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Test
        run: |
          bash .ci/build/client_build.sh 
