name: "testing variables"
on:
  push:

jobs:
  my-job:
    runs-on: self-hosted 
    steps:
      - name: Set Workflow Run ID and Job ID as Environment Variables
        run: |
          echo "Setting environment variables... "
          echo "Job ID: ${GITHUB_JOB}" 
          echo "github run number: ${GITHUB_RUN_NUMBER}"
          echo "id: ${GITHUB_JOB}_${GITHUB_RUN_NUMBER}"
          echo "github workflow number: ${GITHUB_RUN_ID}"
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo "GITHUB_JOB=$GITHUB_JOB" >> $GITHUB_ENV
          echo "GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          echo "GITHUB_RUN_ID=$GITHUB_RUN_ID" >> $GITHUB_ENV
      - name: Use Workflow Run ID and Job ID
        run: |
          echo "Using environment variables..."
          echo "Workflow Run ID: $GITHUB_RUN_ID"
          echo "Job ID: $GITHUB_JOB"
          echo "gITHUB rUN nUMBER : $GITHUB_RUN_NUMBER "
          echo "GITHUB RUN ID: $GITHUB_RUN_ID"
