name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - thinkpranav/x86_64-ubuntu20.04@sha256:667f2b5384785a4e0fcbcbc7a4c6a912fb9008b11789ece6a0ba3964aa3b43e7
        - thinkpranav/x86_64-rocky8.4-mlnx5.4@sha256:056476c3b168526de08a5f102440c9aa1d7b0827a8e91e3ea84065974390b765
     
jobs:
  greet:
    runs-on: self-hosted 
    container:
      image: ${{ github.event.inputs.message }}

    steps:
    - name: Send greeting
      run: echo "${{ github.event.inputs.message }}     ${{ github.event.inputs.name }}"
