name: my workflow
on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV ;  echo "CONCURRENCY=$(nproc)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_SHA_SHORT $CONCURRENCY

   integration-testing:
    needs: build
    runs-on: self-hosted
    steps:
      - run: |
          echo $GITHUB_SHA_SHORT $CONCURRENCY
