name: single and multi job testing 

on:
  workflow_dispatch:
  
    inputs:
      run-specific-job:
        description: 'Run a specific job'
        required: false

jobs:
  build:
    name: Build Job
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Build Application
        run: |
          # Your build commands here

  test:
    name: Test Job
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          # Your test commands here

  specific-job:
    name: Specific Job
    runs-on: self-hosted
    if: github.event.inputs.run-specific-job == 'true'  || github.event.inputs.run-specific-job == '1'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Specific Job
        run: |
          # Your specific job commands here
