name: single and multi-job testing 

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - thinkpranav/x86_64-ubuntu20.04
        - thinkpranav/x86_64-rocky8.4
        - thinkpranav/debian12-amd64
        - All

jobs:
  ubuntu20_04:
    name: Job for Ubuntu 20.04
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'thinkpranav/x86_64-ubuntu20.04'
    container:
       image: thinkpranav/x86_64-ubuntu20.04@sha256:667f2b5384785a4e0fcbcbc7a4c6a912fb9008b11789ece6a0ba3964aa3b43e7
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Client rebuild
        run: |
          cat /etc/os-release 
  rockylinux_8_4:
    name: Client rebuild for rocky8.4
    runs-on: self-hosted
    if:  GitHub.event.inputs.name == 'All'  ||  Github.event.inputs.name == 'thinkpranav/x86_64-rocky8.4'
    container:
       image: thinkpranav/x86_64-rocky8.4-mlnx5.4@sha256:056476c3b168526de08a5f102440c9aa1d7b0827a8e91e3ea84065974390b765
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Tests
        run: |
          cat /etc/redhat-release
  debian_12:
    name: Client rebuild for Debian 12
    runs-on: self-hosted
    if: GitHub.event.inputs.name == 'All'  ||  github.event.inputs.name == 'thinkpranav/debian12-amd64'
    container:
       image: thinkpranav/debian12-client-build@sha256:26130277c017a216b00df43f9e32d2e03d0e6da6a2d17c7e2e345f9f67186619
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run client rebuild for Debian 12
        run: |
          cat /etc/os-release
